DDL.sql
NET-G2/Hotel-Management pull request #3
Opened 2023-09-25 05:34 UTC by SharifovDeveloper

2023-09-25 05:41 UTC, diyorbekaxmatov commented on sql/DDL.sql
> +
All  very Good MuhammadAli

2023-09-25 05:41 UTC, SharifovDeveloper commented
Thank you

2023-09-25 05:53 UTC, diyorbekaxmatov requested changes

2023-09-25 05:53 UTC, diyorbekaxmatov commented on sql/DDL.sql
> +	Total_Price MONEY
Pay attention to the correctness of the lines

2023-09-25 05:54 UTC, SharifovDeveloper commented on sql/DDL.sql
> +	Total_Price MONEY
Thank you I understanded

2023-09-25 06:11 UTC, diyorbekaxmatov approved these changes

2023-09-25 06:11 UTC, diyorbekaxmatov commented on sql/DDL.sql
> +	Serial_Number VARCHAR(255),
Again,this is a mistake

2023-09-25 06:11 UTC, SharifovDeveloper commented on sql/DDL.sql
> +	Serial_Number VARCHAR(255),
Oh Bro ,Sorry

2023-09-25 06:19 UTC, diyorbekaxmatov approved these changes

2023-09-25 06:19 UTC, diyorbekaxmatov commented on sql/DDL.sql
> +
What's the point of using the code in this line?

2023-09-25 06:23 UTC, SharifovDeveloper commented on sql/DDL.sql
> +
This code is used to separate lines

2023-09-25 09:58 UTC, Nabiddinov approved these changes

2023-09-25 09:59 UTC, SharifovDeveloper commented on sql/DDL.sql
> +CREATE TABLE Document
Thank you

2023-12-23 11:55 UTC, Mirazyzz commented
Looks good.

2023-12-23 11:55 UTC, merged