DML.sql
NET-G2/Hotel-Management pull request #4
Opened 2023-09-25 05:34 UTC by diyorbekaxmatov

2023-09-25 05:40 UTC, SharifovDeveloper commented on sql/DML.sql
> +*/
All very Good Diyorbek

2023-09-25 05:47 UTC, diyorbekaxmatov commented on sql/DML.sql
> +*/
Thank you.

2023-09-25 05:47 UTC, diyorbekaxmatov commented on sql/DML.sql
> +*/
Thank you.

2023-09-25 05:50 UTC, SharifovDeveloper requested changes

2023-09-25 05:50 UTC, SharifovDeveloper commented on sql/DML.sql
> +    (14, 801, 8),
Pay attention to the correctness of the lines

2023-09-25 05:52 UTC, diyorbekaxmatov commented on sql/DML.sql
> +    (14, 801, 8),
Okay

2023-09-25 06:25 UTC, SharifovDeveloper approved these changes

2023-09-25 06:25 UTC, SharifovDeveloper commented on sql/DML.sql
> +    (15, 14, 14, '2023-12-01', '2023-12-05', 880.00),
Oh Again, This is a Mistake !

2023-09-25 06:26 UTC, diyorbekaxmatov commented on sql/DML.sql
> +    (15, 14, 14, '2023-12-01', '2023-12-05', 880.00),
Sorry!

2023-12-23 11:55 UTC, Mirazyzz commented
Looks good.

2023-12-23 11:55 UTC, merged